<div>
    @section('content')<p>Estado de cuenta</p>@endsection
    <main class="mx-auto px-4 py-10 sm:px-6 lg:px-8 space-y-6">
        <header class="flex flex-wrap items-center justify-between gap-3">
            <div><h1 class="text-2xl font-bold text-gray-900">Estado de cuenta</h1><p class="text-sm text-gray-500">Consulta financiera por inscripción.</p></div>
            @if($inscripcion)<div class="flex gap-2">@can('register-payments')<a href="{{ route('facturacion.pagos.registrar', $inscripcion->inscripciones_id) }}" class="rounded bg-indigo-600 px-4 py-2 text-white">Registrar pago</a>@endcan<button type="button" wire:click="limpiarSeleccion" class="rounded border px-4 py-2">Cambiar inscripción</button></div>@endif
        </header>

        @unless($inscripcion)
            <section class="rounded-lg border bg-white p-5 shadow-sm" aria-labelledby="buscar-inscripcion">
                <h2 id="buscar-inscripcion" class="text-lg font-semibold">Seleccionar inscripción</h2>
                <div class="mt-4 flex gap-2"><x-forms.input type="search" maxlength="120" class="w-full" wire:model.debounce.300ms="busqueda" placeholder="ID, nombre o apellidos" aria-label="Buscar inscripción"/><button type="button" wire:click="limpiarBusqueda" class="rounded border px-4 py-2">Limpiar</button></div>
                <p class="mt-1 text-xs text-gray-500">Se muestran como máximo 25 coincidencias.</p>
                @if(trim((string) $busqueda) !== '')<div class="mt-4 overflow-x-auto"><table class="w-full text-sm"><thead><tr>@foreach(['Inscripción','Alumno','Curso','Grupo','Estatus','Acción'] as $titulo)<th class="border-b bg-gray-50 p-3 text-left">{{ $titulo }}</th>@endforeach</tr></thead><tbody>
                    @forelse($resultados as $resultado)<tr><td class="border-b p-3">#{{ $resultado->inscripciones_id }}</td><td class="border-b p-3">{{ trim(($resultado->prospecto?->prospectos_nombres ?? '').' '.($resultado->prospecto?->prospectos_apellidos ?? '')) ?: 'Sin configurar' }}</td><td class="border-b p-3">{{ $resultado->cursos?->cursos_descripcion ?? '—' }}</td><td class="border-b p-3">{{ $resultado->grupo?->grupo_nombre ?? '—' }}</td><td class="border-b p-3">{{ ucfirst($resultado->estatus ?? 'Sin configurar') }}</td><td class="border-b p-3"><button type="button" wire:click="seleccionarInscripcion({{ $resultado->inscripciones_id }})" class="text-indigo-700 hover:underline">Ver estado de cuenta</button></td></tr>
                    @empty<tr><td colspan="6" class="p-8 text-center text-gray-500">No se encontraron inscripciones.</td></tr>@endforelse
                </tbody></table></div>@endif
            </section>
        @else
            @php($moneda = $inscripcion->moneda ?: 'Sin configurar')
            <section class="rounded-lg border bg-white p-5 shadow-sm" aria-labelledby="datos-inscripcion">
                <h2 id="datos-inscripcion" class="text-lg font-semibold">{{ trim(($inscripcion->prospecto?->prospectos_nombres ?? '').' '.($inscripcion->prospecto?->prospectos_apellidos ?? '')) ?: 'Sin configurar' }}</h2>
                <dl class="mt-4 grid grid-cols-2 gap-3 text-sm md:grid-cols-4"><div><dt class="text-gray-500">Inscripción</dt><dd>#{{ $inscripcion->inscripciones_id }}</dd></div><div><dt class="text-gray-500">Curso</dt><dd>{{ $inscripcion->cursos?->cursos_descripcion ?? '—' }}</dd></div><div><dt class="text-gray-500">Grupo</dt><dd>{{ $inscripcion->grupo?->grupo_nombre ?? '—' }}</dd></div><div><dt class="text-gray-500">Estatus</dt><dd>{{ ucfirst($inscripcion->estatus ?? 'Sin configurar') }}</dd></div><div><dt class="text-gray-500">Responsable de pago</dt><dd>{{ $inscripcion->responsablePago?->nombre_razon_social ?: 'Sin configurar' }}</dd></div><div><dt class="text-gray-500">Correo</dt><dd>{{ $inscripcion->responsablePago?->correo ?: '—' }}</dd></div><div><dt class="text-gray-500">Teléfono</dt><dd>{{ $inscripcion->responsablePago?->telefono ?: '—' }}</dd></div><div><dt class="text-gray-500">Moneda</dt><dd>{{ $moneda }}</dd></div></dl>
            </section>

            <section aria-label="Resumen financiero" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
                @foreach(['total_cargos'=>'Total de cargos','total_pagado'=>'Total pagado','saldo_pendiente'=>'Saldo pendiente','saldo_vencido'=>'Saldo vencido'] as $clave=>$titulo)<div class="rounded-lg border bg-white p-5 shadow-sm"><p class="text-sm text-gray-500">{{ $titulo }}</p><p class="mt-2 text-2xl font-bold">{{ $moneda }} ${{ $resumen[$clave] }}</p></div>@endforeach
            </section>

            <section class="rounded-lg border bg-white p-5 shadow-sm" aria-labelledby="condiciones"><h2 id="condiciones" class="text-lg font-semibold">Condiciones económicas</h2><dl class="mt-4 grid grid-cols-2 gap-3 text-sm md:grid-cols-4">
                <div><dt class="text-gray-500">Fecha de inicio</dt><dd>{{ $inscripcion->fecha_inicio?->format('Y-m-d') ?? 'Sin configurar' }}</dd></div><div><dt class="text-gray-500">Fecha final</dt><dd>{{ $inscripcion->fecha_fin?->format('Y-m-d') ?? 'Sin configurar' }}</dd></div><div><dt class="text-gray-500">Monto de inscripción</dt><dd>{{ $inscripcion->monto_inscripcion !== null ? $moneda.' $'.number_format($inscripcion->monto_inscripcion, 2, '.', ',') : 'Sin configurar' }}</dd></div><div><dt class="text-gray-500">Monto de mensualidad</dt><dd>{{ $inscripcion->monto_mensualidad !== null ? $moneda.' $'.number_format($inscripcion->monto_mensualidad, 2, '.', ',') : 'Sin configurar' }}</dd></div><div><dt class="text-gray-500">Día de vencimiento</dt><dd>{{ $inscripcion->dia_vencimiento ?? 'Sin configurar' }}</dd></div><div><dt class="text-gray-500">Número de mensualidades</dt><dd>{{ $inscripcion->numero_mensualidades ?? 'Sin configurar' }}</dd></div><div><dt class="text-gray-500">Descuento porcentual</dt><dd>{{ $inscripcion->descuento !== null ? number_format($inscripcion->descuento, 2). '%' : 'Sin configurar' }}</dd></div><div><dt class="text-gray-500">Beca porcentual</dt><dd>{{ $inscripcion->beca !== null ? number_format($inscripcion->beca, 2). '%' : 'Sin configurar' }}</dd></div><div class="col-span-2 md:col-span-4"><dt class="text-gray-500">Observaciones financieras</dt><dd class="whitespace-pre-wrap">{{ $inscripcion->observaciones_financieras ?: 'Sin configurar' }}</dd></div><div><dt class="text-gray-500">Moneda</dt><dd>{{ $moneda }}</dd></div>
            </dl></section>

            <section class="space-y-4" aria-labelledby="cargos"><h2 id="cargos" class="text-lg font-semibold">Cargos por periodo</h2>
                @forelse($gruposCargos as $periodo => $cargos)<div class="overflow-x-auto rounded-lg border bg-white shadow-sm"><h3 class="border-b bg-gray-50 p-4 font-semibold">Periodo {{ $periodo }}</h3><table class="w-full text-sm"><thead><tr>@foreach(['Cargo / concepto','Periodo','Emisión','Vencimiento','Subtotal','Descuento','Recargo','Impuestos','Total','Pagado actual','Saldo pendiente','Estado','Observaciones'] as $titulo)<th class="border-b p-3 text-left whitespace-nowrap">{{ $titulo }}</th>@endforeach</tr></thead><tbody>@foreach($cargos as $cargo)<tr><td class="border-b p-3">#{{ $cargo->cargo_id }} · {{ $cargo->conceptoCobro?->nombre ?? 'Sin concepto' }} <span class="text-gray-500">({{ $cargo->conceptoCobro?->clave ?? '—' }})</span></td><td class="border-b p-3">{{ $cargo->periodo_presentacion }}</td><td class="border-b p-3">{{ $cargo->fecha_emision?->format('Y-m-d') ?? '—' }}</td><td class="border-b p-3">{{ $cargo->fecha_vencimiento?->format('Y-m-d') ?? '—' }}</td>@foreach(['subtotal','descuento','recargo','impuestos'] as $campo)<td class="border-b p-3 whitespace-nowrap">{{ $cargo->moneda }} ${{ number_format($cargo->{$campo}, 2, '.', ',') }}</td>@endforeach<td class="border-b p-3 whitespace-nowrap">{{ $cargo->moneda }} ${{ $cargo->total_actual }}</td><td class="border-b p-3">{{ $cargo->moneda }} ${{ $cargo->pagado_actual }}</td><td class="border-b p-3">{{ $cargo->moneda }} ${{ $cargo->saldo_actual }}</td><td class="border-b p-3">{{ ucfirst($cargo->estado) }}</td><td class="border-b p-3">{{ $cargo->observaciones ?: '—' }}</td></tr>@endforeach</tbody></table></div>
                @empty<div class="rounded-lg border bg-white p-8 text-center text-gray-500">No hay cargos registrados para esta inscripción.</div>@endforelse
            </section>

            <section class="overflow-x-auto rounded-lg border bg-white shadow-sm" aria-labelledby="pagos"><h2 id="pagos" class="border-b p-5 text-lg font-semibold">Historial de pagos</h2><table class="w-full text-sm"><thead><tr>@foreach(['Fecha','Folio','Método','Monto','Estado','Confirmó','Confirmación','Aplicaciones','Recibo','Cancelación'] as $titulo)<th class="border-b bg-gray-50 p-3 text-left">{{ $titulo }}</th>@endforeach</tr></thead><tbody>
                @forelse($pagos as $pago)<tr><td class="border-b p-3 whitespace-nowrap">{{ $pago->fecha_pago?->format('Y-m-d H:i') ?? '—' }}</td><td class="border-b p-3">{{ $pago->folio }}</td><td class="border-b p-3">{{ $pago->metodoPago?->nombre ?? 'Sin configurar' }}</td><td class="border-b p-3 whitespace-nowrap">{{ $pago->moneda }} ${{ number_format($pago->monto, 2, '.', ',') }}</td><td class="border-b p-3">{{ ucfirst($pago->estado) }}</td><td class="border-b p-3">{{ $pago->confirmedBy?->name ?? '—' }}</td><td class="border-b p-3">{{ $pago->fecha_confirmacion?->format('Y-m-d H:i') ?? '—' }}</td><td class="border-b p-3"><ul>@forelse($pago->aplicaciones as $aplicacion)<li>#{{ $aplicacion->cargo_id }} · {{ $aplicacion->cargo?->conceptoCobro?->nombre ?? 'Sin concepto' }}: ${{ number_format($aplicacion->importe_aplicado, 2, '.', ',') }}</li>@empty<li>Sin aplicaciones</li>@endforelse</ul></td><td class="border-b p-3">@if($pago->comprobantePago)<a class="text-indigo-700 hover:underline" href="{{ route('facturacion.comprobantes.descargar', ['pago'=>$pago, 'comprobante'=>$pago->comprobantePago]) }}">{{ $pago->comprobantePago->folio }}</a>@else—@endif</td><td class="border-b p-3">@if($pago->estado === \App\Models\Pago::ESTADO_CANCELADO){{ $pago->motivo_cancelacion ?: 'Sin motivo' }}<br>{{ $pago->fecha_cancelacion?->format('Y-m-d H:i') ?? '—' }}@else—@endif</td></tr>
                @empty<tr><td colspan="10" class="p-8 text-center text-gray-500">No hay pagos registrados para esta inscripción</td></tr>@endforelse
            </tbody></table></section>
        @endunless
    </main>
</div>
