<div class="py-8"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
 <div class="rounded bg-white p-6 shadow"><div class="mb-5 flex items-center justify-between"><h1 class="text-2xl font-semibold text-gray-800">Auditoría financiera</h1><a href="{{ route('facturacion.pagos.index') }}" class="text-indigo-700 hover:underline">Volver a pagos</a></div>
 <div class="mb-5 grid gap-3 md:grid-cols-6"><input wire:model.debounce.400ms="busqueda" class="rounded border-gray-300 md:col-span-2" maxlength="120" placeholder="Folio, alumno o inscripción">
 <select wire:model="accion" class="rounded border-gray-300"><option value="">Todas las acciones</option>@foreach($acciones as $item)<option value="{{ $item }}">{{ str_replace('_',' ',ucfirst($item)) }}</option>@endforeach</select>
 <select wire:model="usuarioId" class="rounded border-gray-300"><option value="">Todos los usuarios</option>@foreach($usuarios as $usuario)<option value="{{ $usuario->id }}">{{ $usuario->name }}</option>@endforeach</select>
 <input type="date" wire:model="fechaDesde" class="rounded border-gray-300"><input type="date" wire:model="fechaHasta" class="rounded border-gray-300"></div>
 @if($fechasInvalidas)<p class="mb-4 text-sm text-red-700">El rango de fechas no es válido.</p>@endif
 <div class="overflow-x-auto"><table class="min-w-full text-sm"><thead><tr class="bg-gray-50 text-left"><th class="p-3">Fecha</th><th class="p-3">Acción</th><th class="p-3">Folio</th><th class="p-3">Alumno</th><th class="p-3">Usuario</th><th class="p-3">IP</th><th class="p-3">Resumen</th></tr></thead><tbody>
 @forelse($auditorias as $item)<tr class="border-t"><td class="p-3 whitespace-nowrap">{{ $item->ocurrido_en?->format('Y-m-d H:i:s') }}</td><td class="p-3">{{ str_replace('_',' ',$item->accion) }}</td><td class="p-3">{{ $item->pago->folio }}</td><td class="p-3">{{ trim(($item->pago->prospecto->prospectos_nombres ?? '').' '.($item->pago->prospecto->prospectos_apellidos ?? '')) ?: '—' }}</td><td class="p-3">{{ $item->usuario->name ?? 'Sistema' }}</td><td class="p-3">{{ $item->ip_address ?: '—' }}</td><td class="p-3"><button wire:click="verDetalle({{ $item->auditoria_pago_id }})" class="text-indigo-700 hover:underline">Ver detalle</button></td></tr>
 @empty<tr><td colspan="7" class="p-6 text-center text-gray-500">No hay eventos para los filtros seleccionados.</td></tr>@endforelse</tbody></table></div>
 <div class="mt-4">{{ $auditorias->links() }}</div></div>
 @if($detalle)<div class="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-40 p-4"><div class="max-h-full w-full max-w-3xl overflow-auto rounded bg-white p-6 shadow-xl"><div class="flex justify-between"><h2 class="text-xl font-semibold">Detalle: {{ $detalle->accion }}</h2><button wire:click="cerrarDetalle" class="text-gray-600">Cerrar</button></div>
 @foreach(['Valores anteriores'=>$detalle->valores_anteriores,'Valores nuevos'=>$detalle->valores_nuevos,'Metadatos'=>$detalle->metadatos] as $titulo=>$datos)<h3 class="mt-5 font-semibold">{{ $titulo }}</h3><pre class="mt-2 overflow-auto rounded bg-gray-100 p-3 text-xs">{{ json_encode($datos ?: [], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre>@endforeach</div></div>@endif
</div></div>
