<div class="p-4 md:p-6 space-y-5">
    <div><h1 class="text-2xl font-bold text-gray-900">Reportes financieros</h1><p class="text-sm text-gray-600">Cobranza usa <strong>fecha de pago</strong> y únicamente pagos confirmados vigentes. Zona horaria: {{ $zona }}; intervalos [inicio, fin del día + 1) y totales separados por moneda.</p></div>
    @if(session('reportes-ok'))<div role="status" class="rounded bg-green-100 p-3 text-green-800">{{ session('reportes-ok') }}</div>@endif
    <nav aria-label="Tipos de reporte" class="flex flex-wrap gap-2">
        @foreach(['grupo'=>'Por grupo','curso'=>'Por curso','periodo'=>'Por período de cargo','metodo'=>'Por método','usuario'=>'Por cajero','vencidos'=>'Saldos vencidos','eventos'=>'Cancelaciones / reembolsos','diario'=>'Resumen diario','cierre'=>'Cierre de caja'] as $key=>$label)
            <button type="button" wire:click="$set('reporte','{{ $key }}')" class="rounded px-3 py-2 text-sm {{ $reporte===$key?'bg-indigo-700 text-white':'border bg-white text-gray-700' }}">{{ $label }}</button>
        @endforeach
    </nav>
    <form wire:submit.prevent="aplicar" class="rounded bg-white p-4 shadow grid grid-cols-1 md:grid-cols-4 gap-3">
        <label class="text-sm">Desde (fecha de pago/evento)<input wire:model.defer="desde" type="date" class="mt-1 w-full rounded border-gray-300">@error('desde')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="text-sm">Hasta<input wire:model.defer="hasta" type="date" class="mt-1 w-full rounded border-gray-300">@error('hasta')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="text-sm">Fecha de corte (vencidos)<input wire:model.defer="corte" type="date" class="mt-1 w-full rounded border-gray-300">@error('corte')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="text-sm">Fecha de caja<input wire:model="fechaCaja" type="date" class="mt-1 w-full rounded border-gray-300">@error('fechaCaja')<span class="text-red-600">{{ $message }}</span>@enderror</label>
        <label class="text-sm">Curso<select wire:model.defer="cursoId" class="mt-1 w-full rounded border-gray-300"><option value="">Todos</option>@foreach($cursos as $x)<option value="{{ $x->cursos_id }}">{{ $x->cursos_descripcion }}</option>@endforeach</select></label>
        <label class="text-sm">Grupo<select wire:model.defer="grupoId" class="mt-1 w-full rounded border-gray-300"><option value="">Todos</option>@foreach($grupos as $x)<option value="{{ $x->grupo_id }}">{{ $x->grupo_nombre }}</option>@endforeach</select></label>
        <label class="text-sm">Método<select wire:model.defer="metodoId" class="mt-1 w-full rounded border-gray-300"><option value="">Todos</option>@foreach($metodos as $x)<option value="{{ $x->metodo_pago_id }}">{{ $x->nombre }}</option>@endforeach</select></label>
        <label class="text-sm">Moneda<input wire:model.defer="moneda" maxlength="3" placeholder="Todas / MXN" class="mt-1 w-full rounded border-gray-300 uppercase"></label>
        <label class="text-sm">Usuario que registró<select wire:model="usuarioId" class="mt-1 w-full rounded border-gray-300"><option value="">Todos</option>@foreach($usuarios as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select></label>
        <label class="text-sm">Cajero que confirmó<select wire:model="cajeroId" class="mt-1 w-full rounded border-gray-300" @if(optional(auth()->user()->role)->roles_codigo==='caja') disabled @endif><option value="">{{ optional(auth()->user()->role)->roles_codigo==='caja' ? auth()->user()->name : 'Yo / todos en reportes generales' }}</option>@foreach($usuarios as $x)<option value="{{ $x->id }}">{{ $x->name }}</option>@endforeach</select></label>
        @if($reporte==='eventos')<label class="text-sm">Tipo<select wire:model.defer="tipoEvento" class="mt-1 w-full rounded border-gray-300"><option value="todos">Todos</option><option value="cancelado">Cancelación</option><option value="reembolsado">Reembolso</option></select></label>@endif
        <div class="md:col-span-4 flex flex-wrap gap-2"><button class="rounded bg-indigo-700 px-4 py-2 text-white">Aplicar</button><button type="button" wire:click="limpiar" class="rounded border px-4 py-2">Limpiar</button>
            @if(in_array($reporte,['grupo','curso','periodo','metodo','usuario','vencidos','eventos'])) @can('export-financial-reports')
                @php($query=array_filter(['desde'=>$desde,'hasta'=>$hasta,'corte'=>$corte,'curso_id'=>$cursoId,'grupo_id'=>$grupoId,'metodo_pago_id'=>$metodoId,'usuario_id'=>$usuarioId,'cajero_id'=>$cajeroId,'moneda'=>$moneda,'tipo_evento'=>$tipoEvento],fn($v)=>$v!==''&&$v!==null))
                <a class="rounded border px-4 py-2" href="{{ route('facturacion.reportes.exportar',array_merge([$reporte,'csv'],$query)) }}">CSV</a><a class="rounded border px-4 py-2" href="{{ route('facturacion.reportes.exportar',array_merge([$reporte,'xlsx'],$query)) }}">Excel (.xlsx)</a>
            @endcan @endif
            @if(in_array($reporte,['diario','cierre'])) @can('export-financial-reports')
                @php($queryCaja=['fecha'=>$fechaCaja,'usuario_id'=>$cajeroSeleccionado])
                <a class="rounded border px-4 py-2" href="{{ route('facturacion.reportes.exportar',array_merge([$reporte,'csv'],$queryCaja)) }}">CSV</a><a class="rounded border px-4 py-2" href="{{ route('facturacion.reportes.exportar',array_merge([$reporte,'xlsx'],$queryCaja)) }}">Excel (.xlsx)</a>
            @endcan @endif
        </div>
    </form>

    @if(in_array($reporte,['grupo','curso','periodo','metodo','usuario']))
        <section class="rounded bg-white shadow overflow-x-auto"><table class="min-w-full text-sm"><caption class="p-3 text-left font-semibold">Cobranza confirmada por {{ $reporte }} (sin cancelados, reembolsados ni borradores)</caption><thead><tr class="bg-gray-100"><th class="p-3 text-left">Dimensión</th><th class="p-3 text-right">Pagos únicos</th><th class="p-3">Moneda</th><th class="p-3 text-right">Monto</th></tr></thead><tbody>@forelse($filas as $r)<tr><td class="border-t p-3">{{ $r['dimension'] }}</td><td class="border-t p-3 text-right">{{ $r['cantidad'] }}</td><td class="border-t p-3 text-center">{{ $r['moneda'] }}</td><td class="border-t p-3 text-right">{{ number_format($r['monto'],2,'.',',') }}</td></tr>@empty<tr><td colspan="4" class="p-6 text-center text-gray-500">No hay resultados para estos filtros.</td></tr>@endforelse</tbody></table></section>
    @elseif($reporte==='vencidos')
        <section class="rounded bg-white shadow overflow-x-auto"><table class="min-w-full text-sm"><caption class="p-3 text-left">Saldo positivo con vencimiento anterior al corte; cancelados excluidos.</caption><thead><tr class="bg-gray-100">@foreach(['Alumno','Curso / grupo','Concepto / período','Vencimiento','Días','Moneda','Total','Pagado','Saldo'] as $h)<th class="p-2 text-left">{{ $h }}</th>@endforeach</tr></thead><tbody>@forelse($filas as $c)<tr><td class="border-t p-2">{{ trim(($c->inscripcion?->prospecto?->prospectos_nombres??'').' '.($c->inscripcion?->prospecto?->prospectos_apellidos??'')) ?: 'Sin alumno' }}</td><td class="border-t p-2">{{ $c->inscripcion?->cursos?->cursos_descripcion?:'Sin curso' }} / {{ $c->inscripcion?->grupo?->grupo_nombre?:'Sin grupo' }}</td><td class="border-t p-2">{{ $c->conceptoCobro?->nombre?:'Sin concepto' }} / {{ $c->periodo_anio&&$c->periodo_mes?sprintf('%04d-%02d',$c->periodo_anio,$c->periodo_mes):'Sin período' }}</td><td class="border-t p-2">{{ $c->fecha_vencimiento?->format('Y-m-d') }}</td><td class="border-t p-2">{{ $c->dias_vencidos }}</td><td class="border-t p-2">{{ $c->moneda }}</td><td class="border-t p-2">{{ $c->total }}</td><td class="border-t p-2">{{ $c->pagado }}</td><td class="border-t p-2">{{ $c->saldo_pendiente }}</td></tr>@empty<tr><td colspan="9" class="p-6 text-center">No hay saldos vencidos.</td></tr>@endforelse</tbody></table></section>
    @elseif($reporte==='eventos')
        <section class="rounded bg-white shadow overflow-x-auto"><p class="p-3 text-sm">Fecha del evento: <code>fecha_cancelacion</code> o <code>fecha_reembolso</code>. El modelo no guarda reembolsos parciales: se informa el monto total del pago. Fechas/actores históricos ausentes se muestran explícitamente.</p><table class="min-w-full text-sm"><thead><tr class="bg-gray-100">@foreach(['Tipo','Folio','Alumno / inscripción','Método','Fecha','Responsable','Moneda / monto','Motivo'] as $h)<th class="p-2 text-left">{{ $h }}</th>@endforeach</tr></thead><tbody>@forelse($filas as $p)<tr><td class="border-t p-2">{{ $p->estado==='cancelado'?'Cancelación':'Reembolso' }}</td><td class="border-t p-2">{{ $p->folio }}</td><td class="border-t p-2">{{ trim(($p->inscripcion?->prospecto?->prospectos_nombres??'').' '.($p->inscripcion?->prospecto?->prospectos_apellidos??'')) ?: 'Sin alumno' }} / #{{ $p->inscripciones_id }}</td><td class="border-t p-2">{{ $p->metodoPago?->nombre?:'Sin método' }}</td><td class="border-t p-2">{{ ($p->estado==='cancelado'?$p->fecha_cancelacion:$p->fecha_reembolso)?->format('Y-m-d H:i')??'Sin fecha histórica' }}</td><td class="border-t p-2">{{ $p->cancelledBy?->name?:'Sin responsable histórico' }}</td><td class="border-t p-2">{{ $p->moneda }} {{ $p->monto }}</td><td class="border-t p-2">{{ $p->motivo_cancelacion?:'Sin motivo registrado' }}</td></tr>@empty<tr><td colspan="8" class="p-6 text-center">No hay eventos.</td></tr>@endforelse</tbody></table></section>
    @elseif(in_array($reporte,['diario','cierre']))
        <section class="rounded bg-white p-4 shadow"><h2 class="font-semibold">Caja {{ $fechaCaja }} — [{{ $diario['inicio']->format('Y-m-d H:i') }}, {{ $diario['fin']->format('Y-m-d H:i') }}) {{ $zona }}</h2><p class="text-sm">Los ingresos pertenecen al cajero indicado por <code>confirmed_by</code>; los ajustes, al actor guardado en <code>cancelled_by</code>. Un reembolso sin actor no se atribuye a una caja nominal. “Efectivo” solo es la clave EFECTIVO; los depósitos no se reclasifican.</p><table class="mt-3 min-w-full text-sm"><thead><tr><th>Método</th><th>Moneda</th><th>Movimientos</th><th>Bruto</th><th>Ajustes</th><th>Neto esperado</th></tr></thead><tbody>@forelse($diario['totales'] as $r)<tr>@foreach(['metodo','moneda','cantidad','bruto','ajustes','neto'] as $k)<td class="border-t p-2">{{ $r[$k] }}</td>@endforeach</tr>@empty<tr><td colspan="6" class="p-5 text-center">Sin movimientos.</td></tr>@endforelse</tbody></table></section>
        @if($reporte==='cierre')<section class="rounded bg-white p-4 shadow">@if($cierreExistente)<h2 class="font-semibold">Cierre inmutable #{{ $cierreExistente->cierre_caja_id }}</h2><p>Cajero: {{ $cierreExistente->cajero?->name }} · Cerró: {{ $cierreExistente->cerradoPor?->name }} · {{ $cierreExistente->cerrado_en?->format('Y-m-d H:i:s') }}</p><pre class="mt-2 overflow-auto text-xs">{{ json_encode(['esperado'=>$cierreExistente->totales_esperados,'contado'=>$cierreExistente->importes_contados,'diferencia'=>$cierreExistente->diferencias],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre>@else @can('close-cash')<h2 class="font-semibold">Registrar cierre</h2><p class="text-sm">Capture cada combinación con movimientos. También puede contar métodos activos con esperado cero para registrar sobrantes. El snapshot no se recalcula ni se reabre.</p><div class="overflow-x-auto"><table class="mt-3 min-w-full text-sm"><thead><tr><th>Método</th><th>Moneda</th><th>Esperado</th><th>Contado</th><th>Diferencia preliminar</th></tr></thead><tbody>@foreach($combinaciones as $clave=>$r)<tr><td class="border-t p-2">{{ $r['metodo'] }}</td><td class="border-t p-2">{{ $r['moneda'] }}</td><td class="border-t p-2">{{ $r['neto'] }}</td><td class="border-t p-2"><input inputmode="decimal" wire:model="contados.{{ $clave }}" class="rounded border-gray-300" placeholder="0.00">@error('contados.'.$clave)<span class="block text-red-600">{{ $message }}</span>@enderror</td><td class="border-t p-2">{{ isset($contados[$clave]) && preg_match('/^(?:0|[1-9]\d{0,11})(?:\.\d{1,2})?$/D',(string)$contados[$clave]) ? number_format((float)$contados[$clave]-(float)$r['neto'],2,'.','') : '—' }}</td></tr>@endforeach</tbody></table></div><label class="mt-3 block">Observaciones<textarea wire:model.defer="observaciones" maxlength="2000" class="mt-1 w-full rounded border-gray-300"></textarea></label><button type="button" wire:click="cerrarCaja" class="mt-3 rounded bg-red-700 px-4 py-2 text-white">Cerrar caja definitivamente</button>@endcan @endif</section>@endif
    @endif
</div>
